---
# This playbook will install mysql and create db user and give permissions.

- name: Install Mysql package
  apt: name={{ item }} update_cache=yes state=installed
  with_items:
   - mysql-server
   - python-mysqldb

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf
  notify:
  - restart mysql

- name: Start Mysql Service
  service: name=mysql state=started enabled=yes

- name: Allow access to MySQL from WebServers
  ufw: rule=allow src="{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
  with_items: groups.webservers

- name: Create Application Database
  mysql_db: name={{ dbname }} state=present

- name: Create Application DB User
  mysql_user: name={{ dbuser }} password={{ upassword }} priv=*.*:ALL host='%' state=present
